### ISSUE TITLE
Failed To Deploy Latest Version

### ISSUE THREAD

**Issue by RomanGoddess** [Anandpskerala/AntiServiceBot#2]
Heroku Says Failed To Deploy The latest Go Language You Rewrote

**Comment by anandpsdev** [comment]
@RomanGoddess Any Logs

**Comment by RomanGoddess** [comment]
> @RomanGoddess Any Logs

![SquarePic_20201225_12422148](https://user-images.githubusercontent.com/53878781/103134079-be8b8300-46ae-11eb-8b92-66136a357226.jpg)

**Comment by anandpsdev** [comment]
@RomanGoddess The issue has been fixed try now
